[features]
seeds = false
skip-lint = false

[programs.localnet]
defai_swap = "877w653ayrjqM6fT5yjCuPuTABo8h7N6ffF3es1HRrxm"
defai_staking = "CvDs2FSKiNAmtdGmY3LaVcCpqAudK3otmrG3ksmUBzpG"
defai_estate = "J8qubfQ5SdvYiJLo5V2mMspZp9as75RePwstVXrtJxo8"
defai_app_factory = "4HsYtGADv25mPs1CqicceHK1BuaLhBD66ZFjZ8jnJZr3"

[programs.devnet]
defai_swap = "877w653ayrjqM6fT5yjCuPuTABo8h7N6ffF3es1HRrxm"
defai_staking = "CvDs2FSKiNAmtdGmY3LaVcCpqAudK3otmrG3ksmUBzpG"
defai_estate = "J8qubfQ5SdvYiJLo5V2mMspZp9as75RePwstVXrtJxo8"
defai_app_factory = "4HsYtGADv25mPs1CqicceHK1BuaLhBD66ZFjZ8jnJZr3"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[test]
startup_wait = 10000
skip_local_validator = true

[workspace]
members = ["defai_swap", "defai_staking", "defai_estate", "defai_app_factory"]
types = "target/types"